#pragma once
#include "NativeGameplayTags.h"

namespace FPGameplayTags
{
	/* Shared Tags */
	// Statuses
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Invincible)
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead)
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Strafing)
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_UnderAttack)
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Attacking)

	/* Attack Tags */
	// Player attacks
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Player_Seed_Melee)
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Player_Seed_Ranged)
	// Enemy attacks
	//	- Mushroom Enemy
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Enemy_Mushroom_Melee)
	//	- Fly Enemy
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Enemy_Fly_Melee)
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Enemy_Fly_Range)
	//	- Wasp Enemy
	FORESTPLATFORMER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Enemy_Wasp_Melee)
}
